/**
 * Load the membership roster into public.members.
 *
 *   npm run members -- "Membre CDN.csv"
 *
 * The CSV is the source of truth and this replaces the table with it: rows that
 * left the export are deleted, rows that stayed have every column rewritten,
 * including the ones the export left blank. A loader that only ever upserts
 * leaves a renamed member reading under their old name and, worse, leaves a
 * cancelled membership sitting in the table looking exactly like a current one.
 *
 * The file itself is never committed — it is 70 people's names, home addresses,
 * phone numbers and what they paid a political party. It stays on the machine
 * of whoever exported it, is loaded from there, and .gitignore keeps it out of
 * the repository. Only the six columns the forum decides with reach the
 * database.
 *
 * Connection comes from DATABASE_URL, as the owner, so RLS on public.members —
 * which denies everything to everyone — does not apply.
 */

import { readFileSync } from "node:fs";
import { Client } from "pg";

const file = process.argv[2] ?? "Membre CDN.csv";

if (!process.env.DATABASE_URL) {
  console.error("DATABASE_URL absent (.env).");
  process.exit(1);
}

/**
 * The export is semicolon-separated, CRLF, and encoded in Latin-1 rather than
 * UTF-8 — read as UTF-8 every accented name in it turns into a replacement
 * character, which is how "Côte-des-Neiges" arrives as "C�te-des-Neiges".
 *
 * Quoting is handled because a member's street or recruiter list may contain
 * the delimiter; a quote doubles itself inside a quoted field, as in RFC 4180.
 */
function parseCsv(text: string, delimiter = ";"): string[][] {
  const rows: string[][] = [];
  let row: string[] = [];
  let field = "";
  let quoted = false;

  for (let i = 0; i < text.length; i++) {
    const char = text[i];

    if (quoted) {
      if (char === '"') {
        if (text[i + 1] === '"') {
          field += '"';
          i++;
        } else {
          quoted = false;
        }
      } else {
        field += char;
      }
      continue;
    }

    if (char === '"') {
      quoted = true;
    } else if (char === delimiter) {
      row.push(field);
      field = "";
    } else if (char === "\n") {
      row.push(field);
      field = "";
      rows.push(row);
      row = [];
    } else if (char !== "\r") {
      field += char;
    }
  }

  // A file that does not end in a newline still has a last row in hand.
  if (field !== "" || row.length > 0) {
    row.push(field);
    rows.push(row);
  }

  return rows.filter((cells) => cells.some((cell) => cell.trim() !== ""));
}

const clean = (value: string | undefined) => (value ?? "").trim();

/** Blank cells in this export are sometimes a single space, sometimes empty. */
const orNull = (value: string | undefined) => {
  const trimmed = clean(value);
  return trimmed === "" ? null : trimmed;
};

/** The export writes dates as YYYY-MM-DD. Anything else is not a date. */
const asDate = (value: string | undefined) => {
  const trimmed = clean(value);
  return /^\d{4}-\d{2}-\d{2}$/.test(trimmed) ? trimmed : null;
};

type Member = {
  email: string;
  memberId: string | null;
  firstName: string;
  lastName: string;
  district: string | null;
  joinedOn: string | null;
  expiresOn: string | null;
};

const rows = parseCsv(readFileSync(file, "latin1"));
if (rows.length < 2) {
  console.error(`${file} : aucune ligne de donnees.`);
  process.exit(1);
}

const header = rows[0].map((cell) => clean(cell));
const at = (name: string) => {
  const index = header.indexOf(name);
  if (index === -1) {
    console.error(`${file} : colonne "${name}" absente. Entetes : ${header.join(", ")}`);
    process.exit(1);
  }
  return index;
};

// Named rather than positional: the export is generated by someone else's tool
// and a column inserted in the middle of it would otherwise load phone numbers
// into the email column without a word of complaint.
const COL = {
  memberId: at("Member_id"),
  lastName: at("Nom"),
  firstName: at("Prénom"),
  email: at("Courriel"),
  expires: at("Expiration du membre"),
  joined: at("Date d'adhésion comme membre"),
  district: at("Membership district"),
};

const byEmail = new Map<string, Member>();
let withoutEmail = 0;
let duplicates = 0;

for (const cells of rows.slice(1)) {
  const email = clean(cells[COL.email]).toLowerCase();

  // A membership with no address on file is a real member who simply cannot
  // sign in — there is nowhere to send the code. Counted and reported rather
  // than dropped in silence, because the person to fix it is the one running
  // this script.
  if (!email.includes("@")) {
    withoutEmail++;
    continue;
  }

  const member: Member = {
    email,
    memberId: orNull(cells[COL.memberId]),
    firstName: clean(cells[COL.firstName]),
    lastName: clean(cells[COL.lastName]),
    district: orNull(cells[COL.district]),
    joinedOn: asDate(cells[COL.joined]),
    expiresOn: asDate(cells[COL.expires]),
  };

  // One address, two memberships — a renewal filed as a second row. The email
  // is the key here, so the one that keeps them signed in longest wins.
  const existing = byEmail.get(email);
  if (existing) {
    duplicates++;
    if ((existing.expiresOn ?? "") >= (member.expiresOn ?? "")) continue;
  }

  byEmail.set(email, member);
}

const members = [...byEmail.values()];
if (members.length === 0) {
  console.error(`${file} : aucune adresse courriel exploitable.`);
  process.exit(1);
}

const client = new Client({
  connectionString: process.env.DATABASE_URL,
  ssl: { rejectUnauthorized: false },
});
await client.connect();

try {
  await client.query("begin");

  const emails = members.map((member) => member.email);

  // Everything the export no longer lists goes, except the rows the demo seed
  // planted for its invented residents — those are marked `seeded` and belong
  // to `supabase/demo-seed.sql`, which is also what deletes them.
  const removed = await client.query(
    "delete from public.members where not seeded and email <> all($1) returning email",
    [emails],
  );

  // One statement, seven arrays unnested into rows. 70 members do not need it
  // to be fast; they do need it to be one round trip inside one transaction, so
  // that a connection dropped part-way leaves the roster as it was rather than
  // half-replaced.
  await client.query(
    `insert into public.members
       (email, member_id, first_name, last_name, district, joined_on, expires_on, synced_at)
     select t.email, t.member_id, t.first_name, t.last_name, t.district,
            t.joined_on, t.expires_on, now()
       from unnest(
         $1::text[], $2::text[], $3::text[], $4::text[], $5::text[], $6::date[], $7::date[]
       ) as t(email, member_id, first_name, last_name, district, joined_on, expires_on)
     on conflict (email) do update set
       member_id  = excluded.member_id,
       first_name = excluded.first_name,
       last_name  = excluded.last_name,
       district   = excluded.district,
       joined_on  = excluded.joined_on,
       expires_on = excluded.expires_on,
       synced_at  = excluded.synced_at,
       -- An address the export lists is a real membership, whatever it was
       -- before. Left out, a demo row that happened to share an address would
       -- keep its marker and survive the next load as a ghost.
       seeded     = false`,
    [
      emails,
      members.map((member) => member.memberId),
      members.map((member) => member.firstName),
      members.map((member) => member.lastName),
      members.map((member) => member.district),
      members.map((member) => member.joinedOn),
      members.map((member) => member.expiresOn),
    ],
  );

  // Accounts that exist but can no longer sign in. Nothing is deleted here —
  // whether a lapsed member's topics come down is a decision for a person, not
  // for a loader — but the count is the one thing this script knows and nobody
  // else does.
  const { rows: locked } = await client.query(
    `select count(*)::int as n
       from auth.users u
      where u.email is not null
        and public.membership_status(u.email) <> 'ok'`,
  );

  await client.query("commit");

  const expired = members.filter(
    (member) => member.expiresOn !== null && member.expiresOn < new Date().toISOString().slice(0, 10),
  ).length;

  console.log(`roster charge depuis ${file}`);
  console.log(`  membres        : ${members.length}`);
  console.log(`  echus          : ${expired} (refuses a la connexion)`);
  console.log(`  sans courriel  : ${withoutEmail} (ne peuvent pas se connecter)`);
  console.log(`  doublons       : ${duplicates} (adhesion la plus longue retenue)`);
  console.log(`  retires        : ${removed.rowCount}`);
  console.log(`  comptes bloques: ${locked[0].n} (compte existant hors roster)`);
} catch (err) {
  await client.query("rollback").catch(() => {});
  console.error(`ECHEC (annule) : ${(err as Error).message}`);
  process.exitCode = 1;
} finally {
  await client.end();
}
