/**
 * Sync borough events from Montréal's open-data feed, by hand.
 *
 *   npm run sync:events                    write straight to the database
 *   npm run sync:events -- --sql out.sql   emit SQL to paste into Supabase
 *
 * The second mode exists because outbound Postgres (5432/6543) is blocked on
 * some networks while HTTPS is not. Rather than stashing a service-role key —
 * a secret that bypasses RLS across the whole API — the run emits a statement
 * file to paste into the SQL editor, which needs no new credential at all.
 *
 * Safe to run repeatedly either way: a run replaces the table's contents in
 * one transaction, so events that disappear upstream disappear here too. At
 * ~300 rows a full replace is cheaper and far more predictable than diffing.
 *
 * The reading and the geocoding live in utils/ingest/events-feed.ts, shared
 * with the daily cron route. This file is only the two ways of writing.
 */

import { writeFileSync } from "node:fs";
import { Client } from "pg";
import { COLS, collectEvents, type EventRow } from "../../utils/ingest/events-feed.ts";

const sqlFlag = process.argv.indexOf("--sql");
const sqlPath = sqlFlag >= 0 ? (process.argv[sqlFlag + 1] ?? "events.sql") : null;

if (!sqlPath && !process.env.DATABASE_URL) {
  console.error("DATABASE_URL absent (.env), ou utiliser --sql <fichier>.");
  process.exit(1);
}

console.log("1/3 telechargement et geocodage…");
const { rows: unique, stats } = await collectEvents();

console.log(
  `     ${stats.districts} districts, ${stats.parks} espaces verts nommes, ${stats.places} lieux publics`,
);
console.log(`     ${stats.events} evenements courants dans l'arrondissement`);
console.log(`     ${stats.byPark} nommes par le parc contenant le point`);
console.log(`     ${stats.byPlace} nommes par le lieu public le plus proche`);
console.log(`     ${stats.unnamed} sans nom de lieu`);
console.log(`     ${stats.outside} points hors des 5 districts`);

if (sqlPath) {
  console.log("2/3 generation SQL…");
  const lit = (v: unknown): string => {
    if (v === null || v === undefined) return "null";
    if (typeof v === "number") return String(v);
    return `'${String(v).replace(/'/g, "''")}'`;
  };
  const body = unique
    .map((p) => `  (${COLS.map((c) => lit(p[c as keyof EventRow])).join(", ")})`)
    .join(",\n");

  const sql =
    `-- Generated by scripts/ingest/events.ts on ${new Date().toISOString()}\n` +
    `-- ${unique.length} events. Paste into the Supabase SQL editor and run.\n\n` +
    `begin;\n\ndelete from borough_events;\n\n` +
    `insert into borough_events (${COLS.join(", ")}) values\n${body};\n\ncommit;\n`;

  writeFileSync(sqlPath, sql, "utf8");
  console.log(
    `     ${unique.length} evenements -> ${sqlPath} (${Math.round(Buffer.byteLength(sql) / 1024)} Ko)`,
  );
  process.exit(0);
}

console.log("2/3 ecriture…");
const client = new Client({
  connectionString: process.env.DATABASE_URL,
  ssl: { rejectUnauthorized: false },
});
await client.connect();

try {
  await client.query("begin");
  // Full replace: an event pulled upstream must vanish here too.
  await client.query("delete from borough_events");

  for (let i = 0; i < unique.length; i += 50) {
    const slice = unique.slice(i, i + 50);
    const values: unknown[] = [];
    const tuples = slice.map((p, k) => {
      COLS.forEach((c) => values.push(p[c as keyof EventRow]));
      return `(${COLS.map((_, n) => `$${k * COLS.length + n + 1}`).join(",")})`;
    });
    await client.query(
      `insert into borough_events (${COLS.join(",")}) values ${tuples.join(",")}`,
      values,
    );
  }
  await client.query("commit");

  console.log("3/3 verification…");
  const { rows: check } = await client.query<{ district: string | null; n: string }>(
    `select district, count(*)::text as n from borough_events group by district order by n desc`,
  );
  for (const r of check) console.log(`     ${r.n.padStart(4)}  ${r.district ?? "(hors districts)"}`);
} catch (err) {
  await client.query("rollback").catch(() => {});
  throw err;
} finally {
  await client.end();
}
